# The goal of this exercise is to create a coin toss program that will randomly tell the user "Heads" or "Tails"

import random # import the random module
heads_or_tails = random.randint(0, 1) 
# Creare a variable to store the random number generated by the randint function
#
if heads_or_tails == 1:
    print("Heads")
else:
    print("Tails")